---
title: Dr. Haibo Pan (潘海波博士)
date: 2021-12-01
output: html_notebook
---

## Education

**Doctor of Philosophy in Marketing, 2016.09-2022.01** </br> *City University of Hong Kong, China*

**Master of Management in Business Administration, 2010.09-2013.01** </br> *Harbin Institute of Technology, China*

**Bachelor of Management in Marketing, 2006.09-2010.09** </br> *Harbin Institute of Technology, China*

## Research Interests

-   **Channel Governance**, with Emphasis on Franchising, Agency Theory, and Institutional Theory

-   **Social Identity Theory** in Consumer Behaviors and Marketing Strategy

## Teaching Interests

-   R and Business Analysis
-   R and Academic Research in Social Science
-   International Marketing
-   Branding Managment

## Ongoing Projects

-   **Pan, Haibo**, and Xu Zheng (2021), "Franchisee Configuration and Franchisee Failure: The Role of Intra- and Inter-Brand Competition", ***Manuscript Preparation for Journal of Marketing Research***. <br> <br>

-   **Pan, Haibo**, and Xu Zheng (2021), "The Higher Ads Spending, The Better Financial Performance? The Role of Franchisee Configuration", ***Manuscript Preparation for Journal of Retailing***. <br> <br>

-   Antia, Kersi D., Xu Zheng and **Haibo Pan** (2021), "The Financial Impact of And Firms' Marketing Response To International Terrorism: 9/11 And The Global Airline Industry", ***Data Analysis Phase***.
