---
title: "Favorite Websites"
date: 2021-12-07
---

***Here are my favorite websites***

## <font color= "black"> General </font>

1.  [Google Scholar](https://scholar.google.com)

2.  [Connected Paper](https://www.connectedpapers.com): paper network

3.  [AMiner](https://www.aminer.org)

4.  [Library Genesis](http://libgen.rs)

5.  [Cloud Research](https://www.cloudresearch.com)

6.  [Scribbr](https://www.scribbr.com): plagiarism checker and proofreading

7.  [UTD 24 Journal List](https://jsom.utdallas.edu/the-utd-top-100-business-school-research-rankings/)

8.  [FT 50 Journal List](https://www.ft.com/content/3405a512-5cbb-11e1-8f1f-00144feabdc0)

9.  [ABS Jounal List 2021](https://www.researchgate.net/publication/352767191_Academic_Journal_Guide_2021_It_was_earlier_ABS_2021_Ranking_list)

## <font color= "black"> Toolkits </font>

1.  [Zotero](https://www.zotero.org)
2.  [Zettr](https://www.zettlr.com)
3.  [RStudio](https://www.rstudio.com)
4.  [OBS Studio](https://obsproject.com/zh-tw)
5.  [Net News Wire](https://netnewswire.com): RSS Reader
6.  [Blender](https://www.blender.org)

## <font color= "black"> Online Database </font>

1.  [50+ free Datasets for Data Science Projects](https://blog.journeyofanalytics.com/50-free-datasets-for-data-science-projects/)

2.  [Kaggle](https://www.kaggle.com): Online Projects

3.  [Chinese Industry Report Search](http://report.seedsufe.com/index)

## <font color= "black"> R Learning </font> {.tabset}

1.  [R Fun](https://rfun.library.duke.edu)

2.  [R Teaching](https://education.rstudio.com/teach/tools/)

3.  [R Documentation](https://www.rdocumentation.org/?=ggplot&=%s)

4.  [What They Forget to Teach you about R](https://rstats.wtf)

### <font color = "gray"> R and Analysis Techniques</font>

5.  [Learning Statistics in R](https://ademos.people.uic.edu/index.html)

6.  [Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html)

7.  [R Linear Regression Bayesian](https://www.rensvandeschoot.com/tutorials/r-linear-regression-bayesian-using-brms/)

8.  [Exploratory Data Analysis](https://edav.info/mosaic.html)

### <font color = "gray">R Packages</font>

11. [Xaringan](https://bookdown.org/yihui/rmarkdown/xaringan.html) for power point

12. [Xaringan Extra](https://pkg.garrickadenbuie.com/xaringanExtra/#/README?id=xaringanextra)

13. [Xaringan Theme Generator](https://pkg.garrickadenbuie.com/xaringanthemer/articles/xaringanthemer.html)

14. [data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)

15. [FactoMineR](http://factominer.free.fr/factomethods/index.html) for factor analysis and clustering analysis

16. [Factoextra](http://www.sthda.com/english/wiki/factoextra-r-package-easy-multivariate-data-analyses-and-elegant-visualization)

17. [lavaan](https://lavaan.ugent.be) for SEM

18. [lme4](https://www.rensvandeschoot.com/tutorials/lme4/) for HLM

19. [ggplot2](https://ggplot2-book.org) for figures

20. [gt](https://gt.rstudio.com/articles/intro-creating-gt-tables.html) for tables

21. [ggpubr](https://rpkgs.datanovia.com/ggpubr/index.html)

22. [sjPlot](https://strengejacke.github.io/sjPlot/)

23. [stargazer](https://www.princeton.edu/~otorres/NiceOutputR.pdf)

### <font color = "gray">R Markdown</font>

24. [Markdown](https://www.markdownguide.org/basic-syntax/)

25. [R Markdown](https://bookdown.org/yihui/rmarkdown/yihui-xie.html)

26. [R Markdown for Scientists](https://rmd4sci.njtierney.com)

27. [R Blogdown](https://bookdown.org/yihui/blogdown/)

28. [R Bookdown](https://bookdown.org/yihui/bookdown/)

## <font color= "black"> Data Analysis Learning </font>

1.  [QCA](https://www.bilibili.com/video/BV1nh411k7o4?p=1)
2.  [Interpreting interaction effect](http://www.jeremydawson.com/slopes.htm)
3.  [P Value](http://p-curve.com)
4.  [Survial Analysis](https://www.rensvandeschoot.com/tutorials/discrete-time-survival/)

## <font color= "black"> Theory Learning </font>

1.  [IS Theory](https://is.theorizeit.org/wiki/Main_Page)

2.  [Management Scales](https://en.wikibooks.org/wiki/Handbook_of_Management_Scales#I)

## <font color= "black"> Image Search </font>

1.  [Logo Search](http://instantlogosearch.com)

2.  [Virtual Background](https://coverr.co/stock-video-footage/zoom-virtual-backgrounds)

3.  [Pexel Video](https://www.pexels.com/videos/)

4.  [Pixaby](https://pixabay.com)

5.  [Font Awesome](https://fontawesome.com)

## Web Design

1.  [CSS](https://www.w3schools.com/css/css_background.asp)

2.  [HTML](https://www.w3schools.com/html/html_intro.asp)

3.  [Color name](https://htmlcolorcodes.com/color-names/)
